services:
  api:
    container_name: api
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped


volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
